//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Manage_AssyLine
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class taixin_dbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new taixin_dbEntities object using the connection string found in the 'taixin_dbEntities' section of the application configuration file.
        /// </summary>
        public taixin_dbEntities() : base("name=taixin_dbEntities", "taixin_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new taixin_dbEntities object.
        /// </summary>
        public taixin_dbEntities(string connectionString) : base(connectionString, "taixin_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new taixin_dbEntities object.
        /// </summary>
        public taixin_dbEntities(EntityConnection connection) : base(connection, "taixin_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

    
}
